import { BackgroundImage } from "../../components/BackgroundImage/BackgroundImage";
import { Wrapper } from "../../components/Wrapper/Wrapper";

export function Footer() {
  return (
    <div className="relative text-neutral-100">
      <BackgroundImage backgroundFixed={true} />
      <Wrapper className="relative z-50 flex flex-col gap-8 py-16">
        <h4 className="text-h4 font-semibold">
          Copyright © Patryk Barć | 2024. All rights reserved.
        </h4>
        <p>
          All content, design, and code on this website are the intellectual
          property of Patryk Barć. <br />
          All rights are reserved. Unauthorized use or reproduction of any part
          of this website without prior written permission is strictly
          prohibited.
        </p>
        <p>
          However, you are permitted to use the passwords generated by this
          website for personal or non-commercial purposes. If you wish to use
          the generated passwords for commercial purposes or require further
          permissions, please contact patrykbarc.design@gmail.com.
        </p>
      </Wrapper>
    </div>
  );
}
